name: TEST
run-name: ${{github.actor}} is testing your projects' units.
on:
  push:
    branches:
      - main

env:
  NODE_ENV: TEST
  POSTGRES_DATABASE_URL: ""
  ORM_STRATEGY: drizzle
  DATABASE_STRATEGY: postgres

jobs:
  test_units:
    name: Testing Project Units
    runs-on: ubuntu-slim
    steps:
      - name: checkout code
        run: echo Checking out code


